# fly.toml app configuration file generated for helsinki-phonebook-2023 on 2023-11-16T17:23:48+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "helsinki-phonebook-2023"
primary_region = "sin"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
