version: "3"

services:
  frontend:
    image: blogapp-frontend-dev
    container_name: blogapp-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/usr/src/app

  backend:
    image: blogapp-backend-dev
    container_name: blogapp-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/app
