version: "3"

services:
  frontend:
    image: blogapp-frontend-prod
    container_name: blogapp-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    image: nginx:alpine
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5173:80
    depends_on:
      - frontend
      - backend

  backend:
    image: blogapp-backend-prod
    container_name: blogapp-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    # ports:
    #   - 3001:3001
